In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [54]:
veriler = pd.read_csv("illness.csv")
veriler

Gender  Heart rate   Temp   RR  SPO2  Condition
0       M          193   36.7  22    98          0
1       M           99   37.2  12    97          0
2       M           80   36.0  29    97          1
3       M           73   36.8  22    98          1
4       M           72   36.0  20    96          0
5       M          116   36.8  22    98          0
6       M           81   37.1  14    96          1
7       M           90   37.0  24    96          0
8       M           97   36.8  16    97          1
9       M          100   37.3  22    99          1
10      F           98   37.0  15    77          1
11      F           91   36.5  18    99          1
12      F           98   36.3  18    89          1
13      F          103   37.2  20    99          0
14      F           92   36.4  18    99          0
15      F           80   36.5  20    98          1
16      F          103   36.4  20    98          1
17      F           81   36.9  16    99          0
18      M          129   37.0  22    96          0
19      M          121   37.6  11    97          1
20      M           80   36.7  29    98          0
21      M           73   37.1  18    96          0
22      M           74   36.7  28    94          1
23      M           96   36.9  26    97          1
24      M           73   37.5  22    97          1
25      M           89   38.0  28    97          1
26      M           70   37.3  24    98          1
27      M          130   39.3  18    98          0
28      F           95   36.9  18    80          0
29      F          114   37.7  14    98          1
30      F           79   37.3  22    97          1
31      F          115   37.6  10    91          0
32      F          100   36.9  21    88          1
33      F          101   37.2  18    98          1
34      F          119   36.7  22    98          0
35      F          105   37.6  16    99          1
36      M          103   36.8  18    96          1
37      M           82   36.5  14    96          0
38      M           93   37.1  20    99          1
39      M           84   36.4  18    98          0
40      M           62   36.3  22    99          1
41      M           83   36.5  18    98          0
42      M           72   37.1  16    97          1
43      M           84   37.3  25    98          0
44      M           79   37.1  14    98          1
45      M           73   36.8  26    98          1
46      F           99   36.8  18    69          0
47      F           96   36.7  24    91          1
48      F           83   36.7  22    98          1
49      F          102   36.5  22    97          1
50      F           94   36.5  24    96          1
51      F          108   36.8  20    98          0
52      F          107   36.4  16    97          0
53      F           76   36.7  16   100          1

In [55]:
Gender = veriler.iloc[:,0:1].values

In [56]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [57]:
Gender[:,0] = le.fit_transform(veriler.iloc[:,0])
Gender

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [58]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [59]:
Gender = ohe.fit_transform(Gender).toarray()
Gender

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [60]:
sonuc = pd.DataFrame(data = Gender[:,:1], index = range(54), columns = ["Gender"])
sonuc

Gender
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
6      0.0
7      0.0
8      0.0
9      0.0
10     1.0
11     1.0
12     1.0
13     1.0
14     1.0
15     1.0
16     1.0
17     1.0
18     0.0
19     0.0
20     0.0
21     0.0
22     0.0
23     0.0
24     0.0
25     0.0
26     0.0
27     0.0
28     1.0
29     1.0
30     1.0
31     1.0
32     1.0
33     1.0
34     1.0
35     1.0
36     0.0
37     0.0
38     0.0
39     0.0
40     0.0
41     0.0
42     0.0
43     0.0
44     0.0
45     0.0
46     1.0
47     1.0
48     1.0
49     1.0
50     1.0
51     1.0
52     1.0
53     1.0

In [61]:
veriler["Gender"] = sonuc
veriler

Gender  Heart rate   Temp   RR  SPO2  Condition
0      0.0          193   36.7  22    98          0
1      0.0           99   37.2  12    97          0
2      0.0           80   36.0  29    97          1
3      0.0           73   36.8  22    98          1
4      0.0           72   36.0  20    96          0
5      0.0          116   36.8  22    98          0
6      0.0           81   37.1  14    96          1
7      0.0           90   37.0  24    96          0
8      0.0           97   36.8  16    97          1
9      0.0          100   37.3  22    99          1
10     1.0           98   37.0  15    77          1
11     1.0           91   36.5  18    99          1
12     1.0           98   36.3  18    89          1
13     1.0          103   37.2  20    99          0
14     1.0           92   36.4  18    99          0
15     1.0           80   36.5  20    98          1
16     1.0          103   36.4  20    98          1
17     1.0           81   36.9  16    99          0
18     0.0          129   37.0  22    96          0
19     0.0          121   37.6  11    97          1
20     0.0           80   36.7  29    98          0
21     0.0           73   37.1  18    96          0
22     0.0           74   36.7  28    94          1
23     0.0           96   36.9  26    97          1
24     0.0           73   37.5  22    97          1
25     0.0           89   38.0  28    97          1
26     0.0           70   37.3  24    98          1
27     0.0          130   39.3  18    98          0
28     1.0           95   36.9  18    80          0
29     1.0          114   37.7  14    98          1
30     1.0           79   37.3  22    97          1
31     1.0          115   37.6  10    91          0
32     1.0          100   36.9  21    88          1
33     1.0          101   37.2  18    98          1
34     1.0          119   36.7  22    98          0
35     1.0          105   37.6  16    99          1
36     0.0          103   36.8  18    96          1
37     0.0           82   36.5  14    96          0
38     0.0           93   37.1  20    99          1
39     0.0           84   36.4  18    98          0
40     0.0           62   36.3  22    99          1
41     0.0           83   36.5  18    98          0
42     0.0           72   37.1  16    97          1
43     0.0           84   37.3  25    98          0
44     0.0           79   37.1  14    98          1
45     0.0           73   36.8  26    98          1
46     1.0           99   36.8  18    69          0
47     1.0           96   36.7  24    91          1
48     1.0           83   36.7  22    98          1
49     1.0          102   36.5  22    97          1
50     1.0           94   36.5  24    96          1
51     1.0          108   36.8  20    98          0
52     1.0          107   36.4  16    97          0
53     1.0           76   36.7  16   100          1

In [62]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(veriler[["RR"]], veriler["Condition"])

LinearRegression()

In [63]:
lr.predict([[20]])

C:\Users\hilal\anaconda3\envs\Hilal\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.59579885])

In [69]:
lr2 = LinearRegression()
lr2.fit(veriler[["Gender", "RR", "SPO2"]], veriler["Condition"])

LinearRegression()

In [70]:
lr2.predict([[1,18,95]])

C:\Users\hilal\anaconda3\envs\Hilal\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.62500331])