In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
veriler = pd.read_csv("veriler.csv")
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [4]:
x = veriler.iloc[:,1:4].values
y = veriler.iloc[:,4:].values

In [5]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train = train_test_split(x,y,test_size = 0.3 , random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_test = sc.fit_transform(x_test)
X_train = sc.fit_transform(x_train)

In [7]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)

C:\Users\hilal\anaconda3\envs\Hilal\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [8]:
y_pred = gnb.predict(X_test)

In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 0, 10],
       [ 0,  5]], dtype=int64)

In [10]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = "entropy")
dtc.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [11]:
y_pred2 = dtc.predict(X_test)

In [12]:
cm = confusion_matrix(y_test, y_pred2)
cm

array([[1, 9],
       [1, 4]], dtype=int64)

In [13]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 10 , criterion = "entropy")
rfc.fit(X_train,y_train)

C:\Users\hilal\anaconda3\envs\Hilal\lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(criterion='entropy', n_estimators=10)

In [14]:
y_pred3 = rfc.predict(X_test)

In [15]:
cm = confusion_matrix(y_test, y_pred3)
cm

array([[2, 8],
       [2, 3]], dtype=int64)